# Package Overview
package_name: regression_model

# Data Files
training_data_file: titanic.csv
test_data_file: test.csv

# Variables
# The variable we are attempting to predict (sale price)
target: survived

pipeline_name: regression_model
pipeline_save_file: regression_model_output_v

# set train/test split
test_size: 0.2

# to set the random seed
random_state: 0

alpha: 0.001


features:
  - sex
  - cabin
  - embarked
  - title
  - age
  - fare

CATEGORICAL_VARIABLES:
  - sex
  - cabin
  - embarked
  - title

NUMERICAL_VARIABLES:
  - age
  - fare

CABIN:
  - cabin